config/routes.rb
Rails.application.routes.draw do
  root to: 'bmi_calculations#index'
  devise_for :users

  resources :bmi_calculations, only: [:index, :create, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bmi_calculation.rb
class BmiCalculation < ApplicationRecord
  validates :height, :weight, presence: true
  belongs_to :user

  def calculate_bmi
    square_height = (height ** 2).to_f
    (weight / square_height).round(3)
  end
end

app/models/bmi_categories.rb
module BMICategories
  INDEX = [
    BMICategory.new([0, 15], 'Very severely underweight'),
    BMICategory.new([15, 16], 'Severely underweight '),
    BMICategory.new([16, 18.5], 'Underweight'),
    BMICategory.new([18.5, 25], 'Normal (healthy weight)'),
    BMICategory.new([25, 30], 'Overweight'),
    BMICategory.new([30, 35], 'Obese Class I (Moderately obese)'),
    BMICategory.new([35, 40], 'Obese Class II (Severely obese)'),
    BMICategory.new([40, 45], 'Obese Class III (Very Severely obese)'),
    BMICategory.new([45, 50], 'Obese Class IV (Morbidly Obese)'),
    BMICategory.new([50, 60], 'Obese Class V (Super Obese)'),
    BMICategory.new([60, 100], 'Obese Class VI (Hyper Obese)')
  ]
end

app/models/bmi_category.rb
class BMICategory
  attr_reader :range, :message

  def initialize(range, message)
    @range = range
    @message = message
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bmi_calculations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout

  private

  def layout
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/bmi_calculations_controller.rb
class BmiCalculationsController < ApplicationController
  def index
    @bmi_calculations = current_user.bmi_calculations
  end

  def new
    @bmi_calculation = BmiCalculation.new
  end

  def create
    bmi_calculation = current_user.bmi_calculations.build(permitted_params)

    if bmi_calculation.save
      redirect_to bmi_calculations_path, notice: 'Your record was created successfully'
    else
      redirect_to bmi_calculations_path, alert: 'There was a problem with your request'
    end
  end

  private

  def permitted_params
    params.require(:bmi_calculation).permit(:height, :weight)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmi_calculations_helper.rb
module BmiCalculationsHelper
  def category_message(bmi)
    category = BMICategories::INDEX.detect do |cat|
      bmi.calculate_bmi.between?(*cat.range)
    end

    category.message
  end
end

app/views/bmi_calculations/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Weight</th>
      <th scope="col">Height</th>
      <th scope="col">BMI</th>
      <th scope="col">Category</th>
    </tr>
  </thead>
  <tbody>
    <% @bmi_calculations.each do |bmi| %>
      <tr>
        <th scope="row"><%= bmi.id %></th>
        <td><%= bmi.weight %></td>
        <td><%= bmi.height %></td>
        <td><%= bmi.calculate_bmi %></td>
        <td><%= category_message(bmi) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bmi_calculations/new.html.erb
<h1>New MBI Calculation</h1>

<%= form_for @bmi_calculation do |f| %>
  <div class="form-group">
    <%= f.text_field :weight, class: 'form-control', placeholder: 'Your weight' %>
    <small id="emailHelp" class="form-text text-muted">Please enter your weight in kilograms.</small>
  </div>

  <div class="form-group">
    <%= f.text_field :height, class: 'form-control', placeholder: 'Your height' %>
    <small id="emailHelp" class="form-text text-muted">Please enter your height in meters.</small>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MBI Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <%= render 'shared/navbar' %>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MBI Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">MBI Calculator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">My Calculations</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Create BMI Calculation', new_bmi_calculation_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <%= link_to 'Log out', destroy_user_session_path, class: 'nav-link', method: :delete %>
    <% end %>
  </div>
</nav>